name: Tag
on:
  workflow_dispatch:
    inputs:
      toBeTagAsLatestV5:
        description: 'The image tag which will be tag as latest-v5'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Pull and push image
        run: |
          docker pull c4wiz/tinymediamanager:v${{ github.event.inputs.toBeTagAsLatestV5 }}
          docker tag c4wiz/tinymediamanager:v${{ github.event.inputs.toBeTagAsLatestV5 }} ${{ secrets.DOCKER_USER }}/tinymediamanager:latest-v5
          docker push c4wiz/tinymediamanager:latest-v5
